version: '3'
services:
  server:
    build:
      dockerfile: Dockerfile
      context: ./
    container_name: docker_server
    restart: unless-stopped
    ports:
      - '8000:8090'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

    # volumes:
    #   - ./:/app
    #   - /app/node_modules/
    #   - /app/node_modules/bcrypt/
